learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
# Template TAGGING
app_name = 'basic_app'
urlpatterns= [
    url(r'^relative/$', views.relative, name= 'relative'),
    url(r'^other/$', views.other, name = 'other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url, include

urlpatterns = [
    url(r'^$', views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context = context_dict)
def other(request):
    return render(request, 'basic_app/other.html')
def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark sticky-top fixed-bottom">
      <div class="container">
        <ul class="navbar-nav">
          <li><a  class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <!-- <li class="nav-item active"><a  class='navbar-link' href="#">Admin</a></li> -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
          </li>
          <!-- <li class="nav-item active"><a  class='navbar-link' href="#">Other</a></li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:other' %}">Other <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">Brand</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="#">Admin <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Other</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav> -->
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO INDEX!</h1>
    <h1>This is index.html page showing!</h1>
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:'99' }}</h1>
    {% endblock %}



<!-- before inheritance code -->
<!-- <!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO INDEX!</h1>

  </body>
</html> -->

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER!</h1>
    <h2>This is an exmample of inheritance!</h2>
    <a href="{% url 'basic_app:relative' %}">relative page</a>
    {% endblock %}




<!-- before inheritance code -->
<!-- <!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO OTHER!</h1>
    <a href="{% url 'basic_app:relative' %}">relative page</a>

  </body>
</html> -->

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATE! </h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN    </a>
    <a href="{% url 'index' %}">LINK TO INDEX!</a>

  </body>
</html>